# Generated by Django 5.0 on 2023-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='market_app/default.png', upload_to='market_app/product_images/'),
        ),
    ]
