# Generated by Django 5.0 on 2024-01-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=12, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Unknown Type', max_length=255),
        ),
    ]
