# Generated by Django 5.0 on 2024-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_product_brand_product_color_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
